/**
 * What this product must say beside advice it generated.
 *
 * ── ⚠ Two findings, one sentence (UX-16 and LEG-05, 24 Aug) ─────────────────
 *
 * **UX-16: the product never says its advice is AI-generated.** The consultant
 * answers in confident prose, the health summary reads as an assessment, and
 * nothing on either screen tells the reader a model wrote it. That is a
 * disclosure problem on its own, and it is also the thing Apple's amended
 * Guideline 5.1.2(i) and the App Privacy questionnaire both circle.
 *
 * **LEG-05: the safety disclaimer lives only on a Terms page nobody opens.** It
 * does not appear where the advice is given — not under a consultant answer,
 * not beside the health score, not on a recall card. A disclaimer at the point
 * of advice is worth far more than one behind a link, and it costs a line of
 * copy.
 *
 * ── Why one module rather than a string per screen ──────────────────────────
 *
 * Because this codebase's most repeated defect is a capability that lives in
 * one client and is silently absent from the other — the health band, the
 * context-kind labels, `VehicleCard`'s unauthorized delete, the markdown
 * tokeniser. A safety disclaimer that says one thing on the phone and another
 * on the web, or appears on one and not the other, is that defect applied to
 * the sentence that limits liability.
 *
 * ── The wording, and what each half is doing ────────────────────────────────
 *
 * It says three things and no more:
 *
 *   1. **A model wrote this.** Not "may contain inaccuracies" — that is a
 *      hedge, not a disclosure, and it does not tell anybody what the thing is.
 *   2. **Check it before acting.** The actionable half.
 *   3. **A qualified person is the authority**, for the categories where being
 *      wrong is expensive or dangerous.
 *
 * ⚠ It deliberately does **not** say "this is not advice". It plainly is
 * advice; the product's whole proposition is that it advises. Claiming
 * otherwise in small print under a paragraph that just recommended a repair is
 * the kind of disclaimer that reads as evasive and persuades nobody, including
 * a court.
 *
 * ── ⚠ "It has never seen your car" — handoff §1.3 ───────────────────────────
 *
 * Added to the two surfaces `CODE_HANDOFF_2026-08-24.md` §1.3 names, and lifted
 * verbatim from `app/terms/page.tsx:51`, where it has always been the sharpest
 * sentence in the document.
 *
 * It is doing work the other clauses cannot. "Written by AI" tells a reader
 * *what* produced the text; "from this car's records" tells them *what it had*.
 * Neither tells them what it **lacked** — and the gap between reading a service
 * history and inspecting a vehicle is the whole of what an owner is at risk of
 * misunderstanding when a confident paragraph recommends a repair. It is also
 * the one claim here that is unarguably, checkably true.
 *
 * ── ⚠ The advisor's name is absent here, and stays absent ──────────────────
 *
 * §1.3's suggested copy reads *"Written by [advisor name]'s AI from your
 * records."* The name was blocked when that was written and is not any more —
 * the advisor is **Jay**, chosen 30 Aug — and this file still does not use it.
 *
 * That is a decision, not an oversight. These sentences exist to tell a reader
 * that a **model** produced the text. A first name in that position reads as a
 * person vouching for it, which is precisely the impression the disclosure is
 * here to prevent: "Jay says your brakes are fine" is a recommendation from
 * somebody, and "written by AI, it has never seen your car" is what actually
 * happened. Jay is the voice everywhere else — the greeting, the turn bylines,
 * the system prompt — and this is the one surface where the machinery should
 * be visible instead of the character.
 *
 * `advice-says-it-is-generated.test.ts` asserts all three failures: no
 * placeholder, no product name, and no persona name.
 */

export type AdviceSurface =
  /** A consultant answer. Free-form prose, the most confident-sounding thing here. */
  | 'consultant'
  /** The health score and its summary. */
  | 'health'
  /** A cost or labour estimate. */
  | 'estimate'
  /** A generated maintenance schedule or mod suggestion. */
  | 'plan';

const DISCLOSURES: Record<AdviceSurface, string> = {
  consultant:
    'Written by AI from this car’s records — it has never seen your car. Check anything important with a qualified mechanic before you act on it.',
  health:
    'Generated by AI from the records on file — it has never seen your car. A summary, not an inspection.',
  estimate:
    'Estimated by AI for comparison. Real prices depend on the shop, the parts and what they find.',
  plan:
    'Suggested by AI from this vehicle’s typical schedule. Your car’s history and your manual come first.',
};

/**
 * The line to render beside generated advice on this surface.
 *
 * ⚠ Always a string — there is no "no disclosure" case, and no parameter that
 * turns it off. A surface that shows generated advice shows this; a surface
 * that would rather not is a surface that should not be showing the advice.
 */
export function adviceDisclosure(surface: AdviceSurface): string {
  return DISCLOSURES[surface];
}

/**
 * ── ⚠ Recalls are deliberately not in this list ─────────────────────────────
 *
 * A recall is **not** generated advice. It is NHTSA's own record, quoted, and
 * putting "written by AI" under it would be false in the direction that gets
 * a safety notice ignored — the one place in this product where a reader
 * hedging is actively dangerous.
 *
 * What a recall card needs instead is the *matching* caveat, which is a
 * different claim and already this product's stated position: campaigns are
 * matched on **year/make/model, not VIN**.
 */
export const RECALL_MATCH_CAVEAT =
  'Recalls are matched by year, make and model — not by your VIN. Check with a dealer to confirm which apply to your car.';
