-- The demo garage's copy uses the punctuation the rest of the product uses.
--
-- ── ⚠ Why this is a migration and not a string change ───────────────────────
--
-- The three demo vehicles' health summaries live in `vehicle_health_summary`,
-- seeded by `20260314142241_seed_demo_vehicles.sql`. Editing that file changes
-- nothing about a database where it has already run: `ON CONFLICT DO NOTHING`
-- means a re-run is a no-op, so the rows that exist keep the text they were
-- created with. The board and the database disagree in both directions here —
-- CLAUDE.md §2 — and only an UPDATE moves the artefact.
--
-- ── What is wrong with them ─────────────────────────────────────────────────
--
-- Hyphens doing em-dash work: "Water pump not yet replaced - failure risk
-- increasing past 60k", "2 open recalls - fuel pump and electrical system",
-- "DCT fluid change overdue - schedule soon". Four consecutive design critiques
-- of the rendered dashboard named it, the last one precisely: hyphens "where
-- the brand's own em-dash voice is established" — the product's own disclosure
-- line reads "Generated by AI from the records on file — it has never seen your
-- car", so the two appear within about 200px of each other and one of them is
-- wrong.
--
-- These strings are ours. They were written as demo copy, not produced by a
-- model, so fixing their punctuation is copy-editing rather than rewriting an
-- assessment — which is a line this product does not cross anywhere else.
--
-- ⚠ Scoped to the three seeded demo vehicles by id. A blanket UPDATE over the
-- table would rewrite model-generated prose for real owners' cars, which is
-- exactly the thing that must not happen: the summary a reader sees has to be
-- the summary the model wrote.

UPDATE vehicle_health_summary
SET
  summary = replace(summary, ' - ', ' — '),
  maintenance_status = replace(maintenance_status, ' - ', ' — '),
  recall_status = replace(recall_status, ' - ', ' — '),
  issues_overview = replace(issues_overview, ' - ', ' — '),
  red_flags = ARRAY(SELECT replace(flag, ' - ', ' — ') FROM unnest(red_flags) AS flag),
  recommendations = ARRAY(
    SELECT replace(item, ' - ', ' — ') FROM unnest(recommendations) AS item
  )
WHERE vehicle_id IN (
  'a1000000-0000-0000-0000-000000000001',
  'a2000000-0000-0000-0000-000000000002',
  'a3000000-0000-0000-0000-000000000003'
);

-- ⚠ Deliberately only ` - `, with spaces on both sides. A bare hyphen is doing
-- real work in these strings — "Stage 1", "year/make/model", "ARP rod bolts" —
-- and `replace` has no word boundaries. The spaced form is the one that is
-- always a dash standing in for an em dash.
--
-- ── The service records carry the same hyphen, in two roles ─────────────────
--
-- `maintenance_line_items` holds it in `shop_name` ("Delicious Tuning -
-- Burlingame CA", where it separates a shop from its city) and in
-- `item_description` ("Cabin Air Filter - OEM Honda", where it separates a part
-- from its brand). Both render on the maintenance page under a serif wordmark,
-- and a design critique named the bare hyphen there specifically.
--
-- ⚠ The spaced-only rule earns its keep most here: "Front Differential Fluid -
-- GL-5 75W-90" becomes "Front Differential Fluid — GL-5 75W-90". The grade and
-- the viscosity keep their own hyphens because those are not spaced, which is
-- exactly the distinction a naive replace would destroy.

UPDATE maintenance_line_items
SET
  shop_name = replace(shop_name, ' - ', ' — '),
  item_description = replace(item_description, ' - ', ' — ')
WHERE vehicle_id IN (
  'a1000000-0000-0000-0000-000000000001',
  'a2000000-0000-0000-0000-000000000002',
  'a3000000-0000-0000-0000-000000000003'
)
AND (shop_name LIKE '% - %' OR item_description LIKE '% - %');
